### ISSUE TITLE
rutil.dms: Util.isHttpsNoCookiesが2回目の呼び出しでエラーになる

### ISSUE THREAD

**Issue by wan111** [rentan/Irvine#2]
Util.isHttpsNoCookiesの2回目の呼び出しで
Dorothy2A.dms - Exception: ENameError => undefined - b
エラーとなります

**Comment by rentan** [comment]
ありがとうございます。
修正しました。

コミットログに #番号 を入れると自動的にクローズされる機能があるので試しに入れてみたのですが
ブランチでコミットして修正の確認が取れてからmasterにマージして自動クローズさせるべきでした。

**Comment by wan111** [comment]
対応ありがとうございます。
今までIrvineスレの方で報告等をさせてもらっていましたが
今後何か報告等が有る場合はIrvineスレかissuesやpull requestかどちらの方がいいでしょうか?

**Comment by rentan** [comment]
どちらでもOKです、楽な方でどうぞ。
Irvineスレは書き込みはしていませんが全て読んでいます。
